version: "3.8"

services:
  mysql-cars:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-cars:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_TCP_PORT: ${TCP_PORT}
    ports:
      - "${TCP_PORT}:${TCP_PORT}"
    expose:
      - "${TCP_PORT}"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - cars-web-app

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - ./:/webapp
    depends_on:
      mysql-cars:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - cars-web-app

volumes:
  mysql-cars:

networks:
  cars-web-app: